apiVersion: v1
kind: ConfigMap
metadata:
  name: digitemp-config
data:
  digitemp.conf: |
    TTY /dev/ttyUSB0
    READ_TIME 1000
    LOG_TYPE 1
    LOG_FORMAT "%b %d %H:%M:%S Sensor %s C: %.2C F: %.2F"
    CNT_FORMAT "%b %d %H:%M:%S Sensor %s #%n %C"
    HUM_FORMAT "%b %d %H:%M:%S Sensor %s C: %.2C F: %.2F H: %h%%"
    SENSORS 1
    ROM 0 0x28 0xFF 0xC2 0x9C 0x31 0x18 0x02 0x49
